spring:
    datasource:
      url: jdbc:postgresql://localhost:5433/todo-list-database
      username: koshechkin
      password: pass
      driver-class-name: org.postgresql.Driver
    mvc:
      view:
        prefix: /WEB-INF/jsp
        suffix: .jsp